# Generated by Django 6.0.2 on 2026-03-12 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expense_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('salary', 'Salary'), ('equipment', 'Equipment'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_expenses',
                'ordering': ['-expense_date', '-id'],
                'indexes': [models.Index(fields=['expense_date'], name='rep_exp_date_idx'), models.Index(fields=['category'], name='rep_exp_cat_idx'), models.Index(fields=['created_at'], name='rep_exp_created_idx')],
            },
        ),
    ]
