# Generated by Django 6.0.2 on 2026-03-12 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('payments', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bill_number', models.CharField(db_index=True, max_length=24, unique=True)),
                ('billing_date', models.DateField()),
                ('cycle_month', models.DateField()),
                ('member_code_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('member_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('original_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('currency', models.CharField(default='AFN', max_length=10)),
                ('is_locked', models.BooleanField(default=False)),
                ('member_full_name_snapshot', models.CharField(max_length=220)),
                ('member_status_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('class_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('plan_label_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='payments.memberfeecycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='members.member')),
                ('schedule_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='schedule.scheduleclass')),
            ],
            options={
                'db_table': 'billing_bills',
                'ordering': ['-billing_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['bill_number'], name='bill_number_idx'), models.Index(fields=['member', 'billing_date'], name='bill_member_date_idx'), models.Index(fields=['payment_status'], name='bill_status_idx'), models.Index(fields=['billing_date'], name='bill_date_idx')],
            },
        ),
    ]
