# Generated by Django 6.0.2 on 2026-03-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('class_code', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'schedule_classes',
                'indexes': [models.Index(fields=['class_code'], name='schcls_code_idx'), models.Index(fields=['name'], name='schcls_name_idx'), models.Index(fields=['is_active'], name='schcls_active_idx'), models.Index(fields=['created_at'], name='schcls_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='schedule.scheduleclass')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_slots', to='staff.trainer')),
            ],
            options={
                'db_table': 'schedule_slots',
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['weekday', 'start_time'], name='schslot_week_start_idx'), models.Index(fields=['trainer'], name='schslot_trainer_idx'), models.Index(fields=['schedule_class'], name='schslot_class_idx'), models.Index(fields=['is_active'], name='schslot_active_idx'), models.Index(fields=['created_at'], name='schslot_created_idx')],
            },
        ),
    ]
