# Generated by Django 6.0.2 on 2026-03-12 06:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('run_time', models.TimeField(default='02:00')),
                ('weekday', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('retention_count', models.PositiveSmallIntegerField(default=7)),
                ('backup_directory', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'system_settings_backup_schedule',
            },
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('default_currency', models.CharField(default='AFN', max_length=10)),
                ('payment_methods_json', models.JSONField(blank=True, default=list)),
                ('default_tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_mode', models.CharField(choices=[('none', 'No default discount'), ('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='none', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('invoice_padding', models.PositiveSmallIntegerField(default=6)),
                ('invoice_next_sequence', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'system_settings_billing',
            },
        ),
        migrations.CreateModel(
            name='GymProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('gym_name', models.CharField(default='Gym MIS', max_length=255)),
                ('gym_logo', models.ImageField(blank=True, null=True, upload_to='settings/gym_logo/')),
                ('address', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('working_hours_json', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'system_settings_gym_profile',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('membership_expiry_alert_enabled', models.BooleanField(default=True)),
                ('membership_expiry_days_before', models.PositiveSmallIntegerField(default=7)),
                ('payment_due_reminder_enabled', models.BooleanField(default=True)),
                ('payment_due_days_before', models.PositiveSmallIntegerField(default=3)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_provider', models.CharField(blank=True, default='', max_length=100)),
                ('sms_sender_id', models.CharField(blank=True, default='', max_length=100)),
                ('sms_api_key_encrypted', models.TextField(blank=True, default='')),
                ('email_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password_encrypted', models.TextField(blank=True, default='')),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'db_table': 'system_settings_notifications',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('min_password_length', models.PositiveSmallIntegerField(default=8)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_lowercase', models.BooleanField(default=True)),
                ('require_number', models.BooleanField(default=True)),
                ('require_special', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('login_attempt_limit', models.PositiveSmallIntegerField(default=5)),
                ('lockout_minutes', models.PositiveSmallIntegerField(default=30)),
            ],
            options={
                'db_table': 'system_settings_security',
            },
        ),
        migrations.CreateModel(
            name='SystemPreferenceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('language', models.CharField(default='en', max_length=20)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=30)),
                ('time_format', models.CharField(default='24h', max_length=20)),
                ('timezone', models.CharField(default='Asia/Kabul', max_length=64)),
            ],
            options={
                'db_table': 'system_settings_preferences',
            },
        ),
        migrations.CreateModel(
            name='MembershipPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('duration_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('duration_months', models.PositiveSmallIntegerField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'system_settings_membership_plan_templates',
                'indexes': [models.Index(fields=['name'], name='system_sett_name_504fe1_idx'), models.Index(fields=['is_active'], name='system_sett_is_acti_d22879_idx')],
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('job_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('restore', 'Restore')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, default='', max_length=1000)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_backup_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_settings_backup_jobs',
                'indexes': [models.Index(fields=['job_type', 'status'], name='system_sett_job_typ_5a59b2_idx'), models.Index(fields=['created_at'], name='system_sett_created_c1ee37_idx')],
            },
        ),
    ]
