# Generated by Django 6.0.2 on 2026-03-10 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('equipment_code', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('item_type', models.CharField(choices=[('machine', 'Machine'), ('accessory', 'Accessory'), ('consumable', 'Consumable')], max_length=20)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('free_weight', 'Free Weight'), ('functional', 'Functional'), ('recovery', 'Recovery'), ('hygiene', 'Hygiene'), ('nutrition', 'Nutrition'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity_on_hand', models.PositiveIntegerField()),
                ('quantity_in_service', models.PositiveIntegerField(default=0)),
                ('machine_status', models.CharField(blank=True, choices=[('operational', 'Operational'), ('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('out_of_order', 'Out of Order'), ('retired', 'Retired')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_equipment',
                'indexes': [models.Index(fields=['equipment_code'], name='inventory_e_equipme_4d9887_idx'), models.Index(fields=['name'], name='inventory_e_name_3aaa43_idx'), models.Index(fields=['item_type'], name='inventory_e_item_ty_eb6af5_idx'), models.Index(fields=['category'], name='inventory_e_categor_bd681c_idx'), models.Index(fields=['machine_status'], name='inventory_e_machine_44fd1c_idx'), models.Index(fields=['quantity_on_hand'], name='inventory_e_quantit_775b96_idx'), models.Index(fields=['created_at'], name='inventory_e_created_c319e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('quantity_adjusted', 'Quantity Adjusted'), ('status_changed', 'Status Changed'), ('deleted', 'Deleted'), ('restored', 'Restored')], max_length=30)),
                ('event_source', models.CharField(choices=[('form_edit', 'Form Edit'), ('adjustment_action', 'Adjustment Action'), ('status_action', 'Status Action'), ('system', 'System')], default='system', max_length=30)),
                ('before_snapshot', models.JSONField(blank=True, null=True)),
                ('after_snapshot', models.JSONField(blank=True, null=True)),
                ('quantity_on_hand_delta', models.IntegerField(blank=True, null=True)),
                ('quantity_in_service_delta', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='inventory.equipment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_equipment_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment'], name='inventory_e_equipme_4969fa_idx'), models.Index(fields=['event_type'], name='inventory_e_event_t_b4c9b0_idx'), models.Index(fields=['event_source'], name='inventory_e_event_s_fdcc12_idx'), models.Index(fields=['created_at'], name='inventory_e_created_66372d_idx')],
            },
        ),
    ]
