# Generated by Django 6.0.2 on 2026-03-10 08:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('late_counts_as_half_day_legacy', models.BooleanField(db_column='late_counts_as_half_day', default=True)),
                ('block_future_dates', models.BooleanField(default=True)),
                ('late_deduction_enabled', models.BooleanField(default=True)),
                ('late_deduction_fraction', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4)),
                ('leave_is_paid', models.BooleanField(default=True)),
                ('missing_as_absent', models.BooleanField(default=True)),
                ('salary_basis', models.CharField(choices=[('calendar_days', 'Calendar Days')], default='calendar_days', max_length=30)),
            ],
            options={
                'db_table': 'attendance_policy',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked_records', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.staff')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-attendance_date', '-id'],
                'indexes': [models.Index(fields=['attendance_date'], name='att_date_idx'), models.Index(fields=['staff', 'attendance_date'], name='att_staff_date_idx'), models.Index(fields=['status'], name='att_status_idx'), models.Index(fields=['created_at'], name='att_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('staff', 'attendance_date'), name='att_rec_unique_staff_date_active')],
            },
        ),
    ]
