# Generated by Django 6.0.2 on 2026-03-10 08:16

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('cycle_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_cycle_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='AFN', max_length=10)),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plan', to='members.member')),
            ],
            options={
                'db_table': 'payments_member_fee_plans',
            },
        ),
        migrations.CreateModel(
            name='MemberFeeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cycle_month', models.DateField()),
                ('base_due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cycle_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_cycles', to='members.member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='payments.memberfeeplan')),
            ],
            options={
                'db_table': 'payments_member_fee_cycles',
            },
        ),
        migrations.CreateModel(
            name='StaffSalaryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period_month', models.DateField()),
                ('gross_salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('currency', models.CharField(default='AFN', max_length=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_periods', to='staff.staff')),
            ],
            options={
                'db_table': 'payments_staff_salary_periods',
            },
        ),
        migrations.CreateModel(
            name='StaffSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('paid_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_salary_payments_created', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='payments.staffsalarypayment')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='staff.staff')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.staffsalaryperiod')),
            ],
            options={
                'db_table': 'payments_staff_salary_payments',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemberFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('paid_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_fee_payments_created', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.memberfeecycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='members.member')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='payments.memberfeepayment')),
            ],
            options={
                'db_table': 'payments_member_fee_payments',
                'ordering': ['-paid_at', '-id'],
                'indexes': [models.Index(fields=['member'], name='pay_mfpmt_member_idx'), models.Index(fields=['cycle'], name='pay_mfpmt_cycle_idx'), models.Index(fields=['paid_at'], name='pay_mfpmt_paid_at_idx'), models.Index(fields=['payment_method'], name='pay_mfpmt_method_idx'), models.Index(fields=['is_reversal'], name='pay_mfpmt_rev_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='memberfeeplan',
            index=models.Index(fields=['member'], name='pay_mfp_member_idx'),
        ),
        migrations.AddIndex(
            model_name='memberfeeplan',
            index=models.Index(fields=['effective_from'], name='pay_mfp_from_idx'),
        ),
        migrations.AddIndex(
            model_name='memberfeeplan',
            index=models.Index(fields=['effective_to'], name='pay_mfp_to_idx'),
        ),
        migrations.AddIndex(
            model_name='memberfeeplan',
            index=models.Index(fields=['currency'], name='pay_mfp_curr_idx'),
        ),
        migrations.AddIndex(
            model_name='memberfeecycle',
            index=models.Index(fields=['member', 'cycle_month'], name='pay_mfc_member_month_idx'),
        ),
        migrations.AddIndex(
            model_name='memberfeecycle',
            index=models.Index(fields=['status'], name='pay_mfc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='memberfeecycle',
            index=models.Index(fields=['cycle_month'], name='pay_mfc_month_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memberfeecycle',
            unique_together={('member', 'cycle_month')},
        ),
        migrations.AddIndex(
            model_name='staffsalaryperiod',
            index=models.Index(fields=['staff', 'period_month'], name='pay_ssp_staff_month_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsalaryperiod',
            index=models.Index(fields=['status'], name='pay_ssp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsalaryperiod',
            index=models.Index(fields=['period_month'], name='pay_ssp_month_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffsalaryperiod',
            unique_together={('staff', 'period_month')},
        ),
        migrations.AddIndex(
            model_name='staffsalarypayment',
            index=models.Index(fields=['staff'], name='pay_sspmt_staff_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsalarypayment',
            index=models.Index(fields=['period'], name='pay_sspmt_period_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsalarypayment',
            index=models.Index(fields=['paid_at'], name='pay_sspmt_paid_at_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsalarypayment',
            index=models.Index(fields=['payment_method'], name='pay_sspmt_method_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsalarypayment',
            index=models.Index(fields=['is_reversal'], name='pay_sspmt_rev_idx'),
        ),
    ]
