# Generated by Django 6.0.2 on 2026-03-12 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('member_code', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('id_card_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='members/profile_pictures/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'members',
                'indexes': [models.Index(fields=['member_code'], name='members_member__04838b_idx'), models.Index(fields=['status'], name='members_status_e4ea77_idx'), models.Index(fields=['phone'], name='members_phone_c64f9d_idx'), models.Index(fields=['last_name'], name='members_last_na_c32184_idx'), models.Index(fields=['created_at'], name='members_created_1df6fe_idx')],
            },
        ),
    ]
