# Generated by Django 6.0.2 on 2026-03-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('staff_code', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('position', models.CharField(choices=[('trainer', 'Trainer'), ('clerk', 'Clerk'), ('manager', 'Manager'), ('cleaner', 'Cleaner'), ('other', 'Other')], max_length=20)),
                ('position_other', models.CharField(blank=True, max_length=120, null=True)),
                ('id_card_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff/profile_pictures/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_hired', models.DateField()),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_currency', models.CharField(default='AFN', max_length=10)),
                ('salary_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], default='unpaid', max_length=10)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('resigned', 'Resigned')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff',
                'indexes': [models.Index(fields=['staff_code'], name='staff_code_idx'), models.Index(fields=['position'], name='staff_pos_idx'), models.Index(fields=['employment_status'], name='staff_emp_st_idx'), models.Index(fields=['salary_status'], name='staff_sal_st_idx'), models.Index(fields=['mobile_number'], name='staff_mobile_idx'), models.Index(fields=['last_name'], name='staff_lname_idx'), models.Index(fields=['date_hired'], name='staff_hired_idx'), models.Index(fields=['created_at'], name='staff_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trainer_code', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_trainers',
                'indexes': [models.Index(fields=['trainer_code'], name='stftr_code_idx'), models.Index(fields=['staff'], name='stftr_staff_idx'), models.Index(fields=['created_at'], name='stftr_created_idx')],
            },
        ),
    ]
