# Generated by Django 6.0.2 on 2026-03-12 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_type', models.CharField(choices=[('member', 'Member'), ('staff', 'Staff')], max_length=20, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'cards_sequences',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('card_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('holder_type', models.CharField(choices=[('member', 'Member'), ('staff', 'Staff')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('qr_value', models.CharField(max_length=120)),
                ('barcode_value', models.CharField(max_length=120)),
                ('regenerate_reason', models.TextField(blank=True, null=True)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cards', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='members.member')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_cards', to='cards.card')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='staff.staff')),
            ],
            options={
                'db_table': 'cards',
                'indexes': [models.Index(fields=['holder_type'], name='cards_holder_type_idx'), models.Index(fields=['member', 'is_current'], name='cards_member_curr_idx'), models.Index(fields=['staff', 'is_current'], name='cards_staff_curr_idx'), models.Index(fields=['created_at'], name='cards_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('holder_type', 'member'), ('member__isnull', False), ('staff__isnull', True)), models.Q(('holder_type', 'staff'), ('staff__isnull', False), ('member__isnull', True)), _connector='OR'), name='cards_holder_fk_chk'), models.UniqueConstraint(condition=models.Q(('is_current', True), ('member__isnull', False)), fields=('member',), name='cards_one_current_member_uniq'), models.UniqueConstraint(condition=models.Q(('is_current', True), ('staff__isnull', False)), fields=('staff',), name='cards_one_current_staff_uniq'), models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('member', 'version'), name='cards_member_version_uniq'), models.UniqueConstraint(condition=models.Q(('staff__isnull', False)), fields=('staff', 'version'), name='cards_staff_version_uniq')],
            },
        ),
    ]
