# Generated by Django 6.0.2 on 2026-03-10 08:15

import core.image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(choices=[('users', 'Users'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('purchases', 'Purchases'), ('customers', 'Customers'), ('finance', 'Finance'), ('reports', 'Reports'), ('settings', 'Settings'), ('product_details', 'Product Details'), ('expense', 'Expense'), ('stock_and_warehouse', 'Stock and Warehouse'), ('currency', 'Currency'), ('units', 'Units'), ('discount', 'Discount'), ('students', 'Students'), ('guardians', 'Guardians'), ('teachers', 'Teachers'), ('staff', 'Staff'), ('classes', 'Classes'), ('attendance', 'Attendance'), ('grades', 'Grades'), ('fees', 'Fees'), ('library', 'Library'), ('exam', 'Exam'), ('members', 'Members'), ('schedule', 'Schedule')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permissions',
                'indexes': [models.Index(fields=['module'], name='permissions_module_2c0512_idx')],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('setting_key', models.CharField(max_length=100)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('setting_image', models.ImageField(blank=True, null=True, upload_to=core.image_path.settings_image_upload_path)),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('image', 'Image')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('notifications', 'Notifications'), ('integration', 'Integration'), ('billing', 'Billing')], default='general', max_length=20)),
            ],
            options={
                'db_table': 'settings',
                'indexes': [models.Index(fields=['setting_key'], name='settings_setting_a14441_idx')],
                'unique_together': {('setting_key',)},
            },
        ),
    ]
